### ISSUE TITLE
Making arcade-imgui into a proper package

### ISSUE THREAD

**Issue by einarf** [kfields/arcade-imgui#2]
Hello

This project can definitely be very useful for some people. There are a few things that should probably be done to make this package more accessible:

* Make a proper package with setup.py so it can be pushed to PyPI and installable with pip
* Make a custom renderer using the `arcade.gl` module instead of pyopengl
* Clean up requirements
* Make examples

I can make a PR on this repo if you are interested in maintaining this package. Otherwise we can always fork it.

**Comment by kfields** [comment]
That sounds great!  I merged eruvanos's PR.  Going to give Poetry a shot.  So far so good.
I published it to PyPi and used it inside a separate project with no problems
I'll clean up the docs.  There sort of confusing right now.
Thanks!

**Comment by einarf** [comment]
Great. I'll see if I can PR a renderer this weekend. Then we can get rid of pyopengl.
