### ISSUE TITLE
Renderer does not work anymore with arcade 2.7.xdev

### ISSUE THREAD

**Issue by eruvanos** [kfields/arcade-imgui#7]
Due to some changes within arcade it looks that the IMGUI renderer has some problems with viewport and rendering.

## Screenshot
<img width="792" alt="image" src="https://user-images.githubusercontent.com/9437863/201520083-fa5bb8cd-1499-454d-9f55-5090ee7058d8.png">

## Requirements

```
pip install arcade==2.7.1.dev5 arcade-imgui
```

## Example code

```
import arcade
import imgui
from arcade_imgui import ArcadeRenderer


class ImageInfo(arcade.Window):

    def __init__(self):
        super().__init__(800, 600, "UI Gallery", resizable=True)

        imgui.create_context()
        self.renderer = ArcadeRenderer(self)

    def on_draw(self):
        self.clear()

        imgui.new_frame()

        imgui.show_demo_window(False)

        imgui.render()
        self.renderer.render(imgui.get_draw_data())


if __name__ == '__main__':
    window = ImageInfo()
    arcade.run()
```

**Comment by kfields** [comment]
Hi,  I just updated the repo to arcade 2.7.1.dev5

I'm not having any issues running your example on Windows 11/RTX2060.
The problem your experiencing looks like a clipping issue inside ImGui.
Can you clone/update this repo and run the example and let me know what happens?
I put it in examples/basic.py

Thanks

**Comment by einarf** [comment]
This is realted to pixel ratio. Retina has 4 pixels per viweport coordiante, It could be something I broke in arcade as well.

The way it works now: Arcade will detect the current pixel ratio and adjust the viewport and scissor box automatically. Externally you only need to deal with "window coordiantes".

Seeing only 1/4th of the screen being covered here it seems like a viewport thing?

**Comment by eruvanos** [comment]
That makes sense, I opened it on a 4k screen.

**Comment by eruvanos** [comment]
Same result with the version from main branch

**Comment by einarf** [comment]
I will boot up the old mac

**Comment by einarf** [comment]
I managed to reproduce on my old retina mac. Not sure where the problem is yet, but definitely viewport related.

**Comment by kfields** [comment]
That makes sense to me looking at the image.  Nice work @einarf.  I wish I could help but I don't have a Mac

**Comment by einarf** [comment]
I'll figure it out. I see that the viewport drops down to 800 x 600 after a couple of frames, so I need a bit more time to hunt down this issue. There is a scissor box being set by arcade-imgui I also need to tweak. We should use the `ctx.scissor` value unstead.

**Comment by einarf** [comment]
@eruvanos can you try master branch now? I think I fixed it.

**Comment by kfields** [comment]
Yay @einarf , our savior!  Works on my machine, anxious to hear from @eruvanos.
So that was it?  Just the scissors?  I was sure it had something to do with `self.io.display_fb_scale` also

**Comment by eruvanos** [comment]
Works again <3 Thank you!
